# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/lead_orders', type: :request do

  # This should return the minimal set of attributes required to create a valid
  # LeadOrder. As you add validations to LeadOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      LeadOrder.create! valid_attributes
      get lead_orders_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      lead_order = LeadOrder.create! valid_attributes
      get lead_order_url(lead_order)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_lead_order_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      lead_order = LeadOrder.create! valid_attributes
      get edit_lead_order_url(lead_order)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new LeadOrder' do
        expect do
          post lead_orders_url, params: { lead_order: valid_attributes }
        end.to change(LeadOrder, :count).by(1)
      end

      it 'redirects to the created lead_order' do
        post lead_orders_url, params: { lead_order: valid_attributes }
        expect(response).to redirect_to(lead_order_url(LeadOrder.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new LeadOrder' do
        expect do
          post lead_orders_url, params: { lead_order: invalid_attributes }
        end.not_to change(LeadOrder, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post lead_orders_url, params: { lead_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested lead_order' do
        lead_order = LeadOrder.create! valid_attributes
        patch lead_order_url(lead_order), params: { lead_order: new_attributes }
        lead_order.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the lead_order' do
        lead_order = LeadOrder.create! valid_attributes
        patch lead_order_url(lead_order), params: { lead_order: new_attributes }
        lead_order.reload
        expect(response).to redirect_to(lead_order_url(lead_order))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        lead_order = LeadOrder.create! valid_attributes
        patch lead_order_url(lead_order), params: { lead_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested lead_order' do
      lead_order = LeadOrder.create! valid_attributes
      expect do
        delete lead_order_url(lead_order)
      end.to change(LeadOrder, :count).by(-1)
    end

    it 'redirects to the lead_orders list' do
      lead_order = LeadOrder.create! valid_attributes
      delete lead_order_url(lead_order)
      expect(response).to redirect_to(lead_orders_url)
    end
  end
end
