# frozen_string_literal: true

# Move this require to your `config/application.rb` if you want to be notified from runner commands too.
require 'exception_notification/rails'

# NOTE: This doesn't work in production
# require 'exception_notification/rake'
# require 'exception_notification/sidekiq'

ExceptionNotification.configure do |config|
  # Ignore additional exception types.
  # ActiveRecord::RecordNotFound, Mongoid::Errors::DocumentNotFound, AbstractController::ActionNotFound and
  # ActionController::RoutingError are already added.
  # config.ignored_exceptions += %w{ActionView::TemplateError CustomError}

  # Adds a condition to decide when an exception must be ignored or not.
  # The ignore_if method can be invoked multiple times to add extra conditions.
  # config.ignore_if do |exception, options|
  #   Rails.env.local?
  # end
  config.ignore_if do |_exception, _options|
    !Rails.env.match?(/production$/)
  end

  # Ignore exceptions generated by crawlers
  # config.ignore_crawlers %w{Googlebot bingbot}

  # Notifiers =================================================================

  # Email notifier sends notifications by email.
  # config.add_notifier :email, {
  #   email_prefix: '[ERROR] ',
  #   sender_address: %("Notifier" <leadsupport@goatleads.com>),
  #   exception_recipients: %w[goatleads@beachghost.com]
  # }

  # Webhook notifier sends notifications over HTTP protocol. Requires 'httparty' gem.
  # config.add_notifier :webhook, {
  #   url: 'http://example.com:5555/hubot/path',
  #   http_method: :post
  # }

  config.add_notifier :slack, {
    webhook_url: Rails.application.credentials.dig(:slack, :webhook_url),
    channel: Settings.notifications.slack_channel
  }
end
