# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so fpostgresqlrom the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: redis
  url: redis://127.0.0.1:6379/1 # Match Sidekiq

test:
  adapter: test

# production:
#   adapter: solid_cable
#   connects_to:
#     database:
#       writing: cable
#   polling_interval: 10.second
#   message_retention: 1.day

production:
  adapter: redis
  url: redis://127.0.0.1:6379/1 # Match Sidekiq and cache
