# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  <% if password = Rails.application.credentials.postgres[:password] %>password: <%= password %><% end %>
  username: <%= Rails.application.credentials.postgres[:user] %>

development:
  primary:
    <<: *default
    database: goat_leads_development
  cache:
    <<: *default
    database: goat_leads_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: goat_leads_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: goat_leads_development_cable
    migrations_paths: db/cable_migrate


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: goat_leads_test

production:
  primary: &primary_production
    <<: *default
    database: goat_leads_production
    username: goat_leads
    password: <%= ENV["GOAT_LEADS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: goat_leads_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: goat_leads_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: goat_leads_production_cable
    migrations_paths: db/cable_migrate
