---
:concurrency: 5

staging:
  :concurrency: 10

production:
  :concurrency: 10

:queues:
  - critical
  - default
  - low
  - mailer

# :scheduler:
#   :schedule:
#     broadcast_widget_updates:
#       every: '5s'
#       class: BroadcastWidgetUpdatesJob
