whitelabel:
  label: goatleads
  site_desc: G.O.A.T. Leads - Exclusive, Top Quality Insurance Leads
  social_desc: Exclusive, Top Quality Insurance Leads
  site_domain: goatleads.com
  site_title: G.O.A.T. Leads
  social_title: G.O.A.T. Leads - Exclusive, Top Quality Insurance Leads
  twitter_handle: "@GoatLeads"
notifications:
  slack_channel: '#goatleads-support'
  email: leadsupport@goatleads.com
  twitter: 'bogus'
